# Application image repository and tag
image:
  repository: spring-kubernetes-helm-i
  tag: 1.2

# Number of replicas for the deployment
replicaCount: 2

# Service configuration
service:
  name: my-spring-app
  type: ClusterIP
  port: 8080

# Application name
appName: my-spring-app

# Ingress configuration (optional)
ingress:
  enabled: true
  host: my-spring-app.example.com # Replace with your actual hostname
  annotations:
    kubernetes.io/ingress.class: nginx # Use the appropriate Ingress controller class

# Autoscaling configuration (optional)
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: true
